"""add_urgency_score_to_todos

Revision ID: 4e6010dbbdcb
Revises: efdb01f63621
Create Date: 2026-04-08 23:13:52.304400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6010dbbdcb'
down_revision: Union[str, None] = 'efdb01f63621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency_score', sa.Float(), nullable=True, server_default='0.0'))
        batch_op.add_column(sa.Column('parent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.drop_column('parent_id')
        batch_op.drop_column('urgency_score')
    # ### end Alembic commands ###
