"""Baseline schema

Revision ID: 641dda489990
Revises: 
Create Date: 2026-03-25 22:55:30.883341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '641dda489990'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Some tables/indexes might already be missing or partially migrated, skipping drops for baseline.
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('neural_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Archivist'"))
        # batch_op.drop_column('wake_names') # Skip if it might already be gone
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('wake_names', sqlite.JSON(), nullable=True))
    op.alter_column('user_settings', 'neural_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Archivist'"))
    op.create_table('marketplace_insights',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('zk_proof_hash', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketplace_insights_provider_id', 'marketplace_insights', ['provider_id'], unique=False)
    # ### end Alembic commands ###
