"""Add known_name to UserPsychology

Revision ID: cc025ca292b4
Revises: 641dda489990
Create Date: 2026-03-26 12:29:12.394519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cc025ca292b4'
down_revision: Union[str, None] = '641dda489990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_psychology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('known_name', sa.String(), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('wake_names')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wake_names', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('user_psychology', schema=None) as batch_op:
        batch_op.drop_column('known_name')

    # ### end Alembic commands ###
