"""add_embedding_to_library_artifact

Revision ID: efdb01f63621
Revises: 523d5e49ca43
Create Date: 2026-04-08 18:00:40.641637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdb01f63621'
down_revision: Union[str, None] = '523d5e49ca43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_artifacts', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
