version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2185:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: ["29095:29092"]
    volumes:
      - kafka_data:/var/lib/kafka/data

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: trader
      POSTGRES_DB: golddb
    ports: ["5435:5432"]
    volumes:
      - tsdb_data:/var/lib/postgresql/data

volumes:
  kafka_data:
  tsdb_data: